from Objects.Title import Title
from Objects.Creditbutton import Creditbutton
from Objects.Startbutton import Startbutton
from Objects.Leavebutton import Leavebutton
from Objects.UltimateFriskus import babum
from Objects.ismettatonWOKEnow import metatito
from Objects.metagun import BONETROUSEL
from Objects.YEEHAW import Lovecraft
from Objects.METAphysics import metatitoo